-- Sample businesses and products for the design preview (is_sample = true).
-- Run AFTER schema.sql, public-submissions.sql and security-and-orders.sql.
-- Remove before launch with:  delete from smes where is_sample;

insert into smes (slug, registered_name, district, llg, primary_industry, secondary_industry, description, photo_ref, hero_photo_ref, featured, consent, approved, approved_at, is_sample) values ('abuta', 'Abuta Agro Services', 'Gazelle', 'Rakunai Village, Central Gazelle LLG', 'produce', null, 'A family-run cocoa nursery at Rakunai Village in Central Gazelle, raising healthy bagged cocoa seedlings for smallholder growers across the Gazelle Peninsula. Every seedling is grown under shade cloth and hardened off before sale, so it is ready to plant out the day it leaves the nursery. Bulk orders for new blocks and replanting are welcome.', 'GAZELLE_Abuta_business_01.jpg', 'GAZELLE_Abuta_frontpage_01.jpg', true, true, true, now(), true) on conflict (slug) do nothing;
insert into smes (slug, registered_name, district, llg, primary_industry, secondary_industry, description, photo_ref, hero_photo_ref, featured, consent, approved, approved_at, is_sample) values ('vunamami', 'Vunamami Growers Collective', 'Kokopo', null, 'produce', 'foodcrops', 'Smallholder growers from Vunamami village supplying fresh garden produce, vanilla and food crops across Kokopo District.', null, 'https://images.unsplash.com/photo-1533900298318-6b8da08a523e', true, true, true, now(), true) on conflict (slug) do nothing;
insert into smes (slug, registered_name, district, llg, primary_industry, secondary_industry, description, photo_ref, hero_photo_ref, featured, consent, approved, approved_at, is_sample) values ('weavers', 'Rabaul Weavers Guild', 'Rabaul', null, 'crafts', 'tailoring', 'A collective of weavers and tailors in Rabaul producing fine bilum, shellcraft and hand-finished garments.', null, 'https://images.unsplash.com/photo-1601330862030-1e08c703ac04', true, true, true, now(), true) on conflict (slug) do nothing;
insert into smes (slug, registered_name, district, llg, primary_industry, secondary_industry, description, photo_ref, hero_photo_ref, featured, consent, approved, approved_at, is_sample) values ('kerevat', 'Kerevat Mill Co.', 'Gazelle', null, 'processing', 'wholesale', 'Processing cocoa, coffee and copra grown around Kerevat, with bulk supply for trade stores across Gazelle District.', null, 'https://images.unsplash.com/photo-1573710661345-610f790e1218', true, true, true, now(), true) on conflict (slug) do nothing;
insert into smes (slug, registered_name, district, llg, primary_industry, secondary_industry, description, photo_ref, hero_photo_ref, featured, consent, approved, approved_at, is_sample) values ('pomio', 'Pomio Forest Crafts', 'Pomio', null, 'crafts', 'processing', 'Carvers and honey producers working from inland Pomio, bringing forest-sourced goods to the wider province.', null, 'https://images.unsplash.com/photo-1517137744310-173515c62d59', true, true, true, now(), true) on conflict (slug) do nothing;
insert into smes (slug, registered_name, district, llg, primary_industry, secondary_industry, description, photo_ref, hero_photo_ref, featured, consent, approved, approved_at, is_sample) values ('toma', 'Toma Tailoring Centre', 'Gazelle', null, 'tailoring', null, 'A tailoring workshop in Toma producing made-to-measure garments and school uniforms for families across Gazelle.', null, 'https://images.unsplash.com/photo-1718184021018-d2158af6b321', true, true, true, now(), true) on conflict (slug) do nothing;
insert into smes (slug, registered_name, district, llg, primary_industry, secondary_industry, description, photo_ref, hero_photo_ref, featured, consent, approved, approved_at, is_sample) values ('ktrade', 'Kokopo Trade Supplies', 'Kokopo', null, 'retail', 'wholesale', 'A long-established trade store in Kokopo supplying household goods, stationery and bulk essentials.', null, 'https://images.unsplash.com/photo-1663154438428-60cdc204f99b', true, true, true, now(), true) on conflict (slug) do nothing;
with np as (insert into products (sme_id, name, category, price, unit, stock, description, perishable, status, badge, sort_key) select id, 'Cocoa Seedlings, Bagged & Ready to Plant', 'produce', 3, 'per seedling', 4800, 'Healthy cocoa seedlings raised in poly bags under shade cloth at Rakunai Village. Hardened off and ready to plant straight into the ground. Collect from the nursery in Central Gazelle, or order in bulk for delivery.', true, 'live', 'Local grower', 0 from smes where slug = 'abuta' returning id) insert into product_images (product_id, storage_path, photo_ref, sort_order) select id, 'GAZELLE_Abuta_seedlings_01.jpg', 'GAZELLE_Abuta_seedlings_01.jpg', 0 from np;
with np as (insert into products (sme_id, name, category, price, unit, stock, description, perishable, status, badge, sort_key) select id, 'Cocoa Seedlings, Block Planting Pack (500)', 'produce', 1500, 'per 500 seedlings', 9, 'Five hundred bagged cocoa seedlings for planting a new block or replacing ageing trees — the same K3 a seedling, ready in one lot. Please allow around three weeks for large orders so the nursery can set aside hardened stock.', true, 'live', 'Bulk', 1 from smes where slug = 'abuta' returning id) insert into product_images (product_id, storage_path, photo_ref, sort_order) select id, 'GAZELLE_Abuta_seedlings_02.jpg', 'GAZELLE_Abuta_seedlings_02.jpg', 0 from np;
with np as (insert into products (sme_id, name, category, price, unit, stock, description, perishable, status, badge, sort_key) select id, 'Single-Origin Cocoa, Hand Fermented (1kg)', 'processing', 52, 'per kg', 34, 'Hand-fermented at the Kerevat mill from cocoa grown within Gazelle District.', false, 'live', 'Signature', 2 from smes where slug = 'kerevat' returning id) insert into product_images (product_id, storage_path, photo_ref, sort_order) select id, 'https://images.unsplash.com/photo-1573710661345-610f790e1218?fm=jpg&q=72&w=820&auto=format&fit=crop', 'photo-1573710661345-610f790e1218', 0 from np;
with np as (insert into products (sme_id, name, category, price, unit, stock, description, perishable, status, badge, sort_key) select id, 'Fine-Weave Bilum, Large', 'crafts', 135, 'each', 6, 'Hand-woven over several weeks using traditional Tolai patterns.', false, 'live', null, 3 from smes where slug = 'weavers' returning id) insert into product_images (product_id, storage_path, photo_ref, sort_order) select id, 'https://images.unsplash.com/photo-1601330862030-1e08c703ac04?fm=jpg&q=72&w=820&auto=format&fit=crop', 'photo-1601330862030-1e08c703ac04', 0 from np;
with np as (insert into products (sme_id, name, category, price, unit, stock, description, perishable, status, badge, sort_key) select id, 'Volcanic Soil Vanilla Beans (100g)', 'foodcrops', 88, 'per 100g', 18, 'Grown in the mineral-rich volcanic soil around Kokopo.', false, 'live', 'Best seller', 4 from smes where slug = 'vunamami' returning id) insert into product_images (product_id, storage_path, photo_ref, sort_order) select id, 'https://images.unsplash.com/photo-1682482198446-4cbf92f85a4b?fm=jpg&q=72&w=820&auto=format&fit=crop', 'photo-1682482198446-4cbf92f85a4b', 0 from np;
with np as (insert into products (sme_id, name, category, price, unit, stock, description, perishable, status, badge, sort_key) select id, 'Baining Mountain Coffee (250g)', 'processing', 40, 'per bag', 25, 'Shade-grown coffee from the Baining ranges, roasted at Kerevat.', false, 'live', 'New', 5 from smes where slug = 'kerevat' returning id) insert into product_images (product_id, storage_path, photo_ref, sort_order) select id, 'https://images.unsplash.com/photo-1642258632706-142d5ce17754?fm=jpg&q=72&w=820&auto=format&fit=crop', 'photo-1642258632706-142d5ce17754', 0 from np;
with np as (insert into products (sme_id, name, category, price, unit, stock, description, perishable, status, badge, sort_key) select id, 'Island Spice Blend (150g)', 'foodcrops', 26, 'per 150g', 40, 'A house blend of island-grown spices.', false, 'live', null, 6 from smes where slug = 'vunamami' returning id) insert into product_images (product_id, storage_path, photo_ref, sort_order) select id, 'https://images.unsplash.com/photo-1716816211590-c15a328a5ff0?fm=jpg&q=72&w=820&auto=format&fit=crop', 'photo-1716816211590-c15a328a5ff0', 0 from np;
with np as (insert into products (sme_id, name, category, price, unit, stock, description, perishable, status, badge, sort_key) select id, 'Dried Chilli Powder (100g)', 'foodcrops', 18, 'per 100g', 30, 'Sun-dried and ground chillies from the Vunamami gardens.', false, 'live', null, 7 from smes where slug = 'vunamami' returning id) insert into product_images (product_id, storage_path, photo_ref, sort_order) select id, 'https://images.unsplash.com/photo-1547332226-395d746d139a?fm=jpg&q=72&w=820&auto=format&fit=crop', 'photo-1547332226-395d746d139a', 0 from np;
with np as (insert into products (sme_id, name, category, price, unit, stock, description, perishable, status, badge, sort_key) select id, 'Highlands Rice, Milled (5kg)', 'foodcrops', 62, 'per 5kg bag', 50, 'Milled rice sold by the bag, ready for the trade store shelf.', false, 'live', null, 8 from smes where slug = 'ktrade' returning id) insert into product_images (product_id, storage_path, photo_ref, sort_order) select id, 'https://images.unsplash.com/flagged/photo-1553617569-8ef7a8da3146?fm=jpg&q=72&w=820&auto=format&fit=crop', 'photo-1553617569-8ef7a8da3146', 0 from np;
with np as (insert into products (sme_id, name, category, price, unit, stock, description, perishable, status, badge, sort_key) select id, 'Meri Blouse, Made to Measure', 'tailoring', 95, 'each', 8, 'Made to measure at the Toma workshop — allow one week.', false, 'live', null, 9 from smes where slug = 'toma' returning id) insert into product_images (product_id, storage_path, photo_ref, sort_order) select id, 'https://images.unsplash.com/photo-1633655442432-620aa55d7ac1?fm=jpg&q=72&w=820&auto=format&fit=crop', 'photo-1633655442432-620aa55d7ac1', 0 from np;
with np as (insert into products (sme_id, name, category, price, unit, stock, description, perishable, status, badge, sort_key) select id, 'School Uniform Set, Tailored', 'tailoring', 78, 'per set', 15, 'Tailored uniform sets, sized for primary and secondary students.', false, 'live', 'Seasonal', 10 from smes where slug = 'toma' returning id) insert into product_images (product_id, storage_path, photo_ref, sort_order) select id, 'https://images.unsplash.com/photo-1618587194716-40490bdba417?fm=jpg&q=72&w=820&auto=format&fit=crop', 'photo-1618587194716-40490bdba417', 0 from np;
with np as (insert into products (sme_id, name, category, price, unit, stock, description, perishable, status, badge, sort_key) select id, 'Laplap, Hand-Finished', 'tailoring', 45, 'each', 20, 'Hand-finished laplap in a range of island prints.', false, 'live', null, 11 from smes where slug = 'weavers' returning id) insert into product_images (product_id, storage_path, photo_ref, sort_order) select id, 'https://images.unsplash.com/photo-1718184021018-d2158af6b321?fm=jpg&q=72&w=820&auto=format&fit=crop', 'photo-1718184021018-d2158af6b321', 0 from np;
with np as (insert into products (sme_id, name, category, price, unit, stock, description, perishable, status, badge, sort_key) select id, 'Wild Forest Honey (350ml)', 'processing', 45, 'per 350ml', 12, 'Harvested from wild hives in the Pomio forest.', false, 'live', null, 12 from smes where slug = 'pomio' returning id) insert into product_images (product_id, storage_path, photo_ref, sort_order) select id, 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?fm=jpg&q=72&w=820&auto=format&fit=crop', 'photo-1558642452-9d2a7deb7f62', 0 from np;
with np as (insert into products (sme_id, name, category, price, unit, stock, description, perishable, status, badge, sort_key) select id, 'Smoked Reef Fish, Whole', 'processing', 38, 'each', 10, 'Smoked the same day it is caught.', true, 'live', null, 13 from smes where slug = 'vunamami' returning id) insert into product_images (product_id, storage_path, photo_ref, sort_order) select id, 'https://images.unsplash.com/photo-1739484151190-e2a73842ca13?fm=jpg&q=72&w=820&auto=format&fit=crop', 'photo-1739484151190-e2a73842ca13', 0 from np;
with np as (insert into products (sme_id, name, category, price, unit, stock, description, perishable, status, badge, sort_key) select id, 'Cooking Bananas (Bunch)', 'produce', 18, 'per bunch', 22, 'Fresh-cut cooking bananas from the Vunamami gardens.', true, 'live', null, 14 from smes where slug = 'vunamami' returning id) insert into product_images (product_id, storage_path, photo_ref, sort_order) select id, 'https://images.unsplash.com/photo-1706059924238-361c705b121f?fm=jpg&q=72&w=820&auto=format&fit=crop', 'photo-1706059924238-361c705b121f', 0 from np;
with np as (insert into products (sme_id, name, category, price, unit, stock, description, perishable, status, badge, sort_key) select id, 'Aibika Greens Bundle', 'produce', 12, 'per bundle', 40, 'Cut fresh each morning.', true, 'live', 'Fresh today', 15 from smes where slug = 'vunamami' returning id) select 1 from np;
with np as (insert into products (sme_id, name, category, price, unit, stock, description, perishable, status, badge, sort_key) select id, 'Fresh Taro (5kg bag)', 'produce', 35, 'per 5kg bag', 16, null, true, 'live', null, 16 from smes where slug = 'kerevat' returning id) select 1 from np;
with np as (insert into products (sme_id, name, category, price, unit, stock, description, perishable, status, badge, sort_key) select id, 'Handcarved Ebony Figure', 'crafts', 225, 'each', 3, 'Carved by hand from a single piece of ebony.', false, 'live', null, 17 from smes where slug = 'pomio' returning id) select 1 from np;
with np as (insert into products (sme_id, name, category, price, unit, stock, description, perishable, status, badge, sort_key) select id, 'Shell & Seed Necklace', 'crafts', 60, 'each', 11, null, false, 'live', null, 18 from smes where slug = 'weavers' returning id) select 1 from np;
with np as (insert into products (sme_id, name, category, price, unit, stock, description, perishable, status, badge, sort_key) select id, 'Cold-Pressed Copra Oil (500ml)', 'processing', 32, 'per 500ml', 28, null, false, 'live', null, 19 from smes where slug = 'kerevat' returning id) select 1 from np;
with np as (insert into products (sme_id, name, category, price, unit, stock, description, perishable, status, badge, sort_key) select id, 'Copra Oil, 20L Bulk Drum', 'wholesale', 520, 'per drum', 4, null, false, 'live', 'Bulk', 20 from smes where slug = 'kerevat' returning id) select 1 from np;
with np as (insert into products (sme_id, name, category, price, unit, stock, description, perishable, status, badge, sort_key) select id, 'Trade Store Starter Pack', 'wholesale', 340, 'per pack', 7, null, false, 'live', 'Bulk', 21 from smes where slug = 'ktrade' returning id) select 1 from np;
with np as (insert into products (sme_id, name, category, price, unit, stock, description, perishable, status, badge, sort_key) select id, 'Household Goods Bundle', 'retail', 85, 'per bundle', 14, null, false, 'live', null, 22 from smes where slug = 'ktrade' returning id) select 1 from np;
with np as (insert into products (sme_id, name, category, price, unit, stock, description, perishable, status, badge, sort_key) select id, 'Stationery & School Supplies Pack', 'retail', 55, 'per pack', 19, null, false, 'live', null, 23 from smes where slug = 'ktrade' returning id) select 1 from np;
